### ISSUE TITLE
Hero

### ISSUE THREAD

**Issue by thehighestprimenumber** [programar101/code101lp#3]
![image](https://user-images.githubusercontent.com/11212953/146943036-4df3ec7a-d023-4b6a-b9c9-62edddd0dffd.png)

**Comment by thehighestprimenumber** [comment]
@ricmonmol a dónde nos lleva el botón de información?
el de "inscribirme" por ahora puede quedar vacío, vemos como venimos con los tiempos, nos lleva a un google form o a un formulario que hagamos en HTML.

**Comment by ricmonmol** [comment]
El "información" en Educación IT lleva a un pdf, quizá lo podemos obviar en este caso.

**Comment by CarballoChr** [comment]
Quizás el botón  nos puede llevar a una sección con la fecha de inicio, requisitos para la inscripción, etc.
